### ISSUE TITLE
fluffy.pyw crash without icon.ico

### ISSUE THREAD

**Issue by nxmango** [fourminute/Fluffy#1]
Maybe add the ability to launch without the icon? or doing a executable?
I really like your project, it's a great improvement over TUG! :)

**Comment by fourminute** [comment]
Thank you for the support nxmango, I really appreciate it! I'm actually going to include the icon in the code itself using URI format for the image. That will be in the next version for sure!

**Comment by fourminute** [comment]
Fixed in v1.3
