### ISSUE TITLE
Use a requirements.txt for easy library installation (diff attached for easy merge)

### ISSUE THREAD

**Issue by Zer0t3ch** [fourminute/Fluffy#10]
Here's a diff you can use that's all set up. Should match the requirements listed in the readme.

http://susepaste.org/view//45153638

```
diff --git a/requirements.txt b/requirements.txt
new file mode 100644
index 0000000..6b82644
--- /dev/null
+++ b/requirements.txt
@@ -0,0 +1,4 @@
+qdarkstyle
+pyqt5
+pyusb
+libusb
```

If you've never used one, [here's a page](https://pip.pypa.io/en/stable/user_guide/#requirements-files) on how they work and what they're for. In this case, they only really serve to make things easier for end-users.

**Comment by fourminute** [comment]
I would like to give you credit for this code change, is it possible to create a pull with this file? Thank you.

**Comment by Zer0t3ch** [comment]
Sure, I'll take care of it when I get home tonight, and I'll include some additional tweaks to the README along with it so the instructions match the new file. Thanks for your consideration.
