### ISSUE TITLE
Arch package and fluffy icon

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#12]
I made an AUR package for fluffy: https://aur.archlinux.org/packages/fluffy-switch/
It's renamed fluffy-switch to avoid confusion with an other package named fluffy-git.

It still launched via terminal for now, I wanted to know if you have an svg of the icon ?
If not a png of 128px will be better than the 48px one.

**Comment by fourminute** [comment]
Awesome! Thank you!
I don't have a proper SVG icon yet, you're right on the 48px size. I'll look into making it smaller.

**Comment by YoyPa** [comment]
> I'll look into making it smaller.

Smaller ? not sure of what you mean :open_mouth: 
I already made a little Imagemagick script to make 128/64/48/32/34/16px, just wanted an original >=128.

**Comment by fourminute** [comment]
Oh dang I just realized my mistake. Yes my icon was an accident. I didn't mean to choose such a small icon. I have the extra large version I will change it.

**Comment by fourminute** [comment]
I have updated the icon in the master branch go check it out!
