### ISSUE TITLE
Improved Install.sh and an official PPA

### ISSUE THREAD

**Issue by fourminute** [fourminute/Fluffy#14]
I've uploaded the Install.sh script under the Linux folder. It's going to take a while to get it right, but currently it works under Ubuntu/Debian. I'm going to keep this issue open for the time being so discussion can be done on making improvements. 

https://github.com/fourminute/Fluffy/blob/master/linux/install.sh

I am also looking into creating a PPA. Any and all advice is appreciated.

**Comment by YoyPa** [comment]
It's a bit of a joke but :tada:**arch wiki**:tada:  describe the howto for major distribution packaging and they also mention https://openbuildservice.org/ which seems OP but interesting (no clue how to use it).
https://wiki.archlinux.org/index.php/Creating_packages_for_other_distributions
The first sentence of the page is epic, /!\ do not click on it without sunglasses /!\

**Comment by fourminute** [comment]
Actually I have decided to not go the PPA route or include installation. I think fluffy does fine as a portable format.
