### ISSUE TITLE
OSX: Slow reaction and loading times

### ISSUE THREAD

**Issue by lookye** [fourminute/Fluffy#16]
I am using a 2017 Mac, everything needed is installed. 
When I am starting Fluffy it loads, but reacts extremly slow and the loading circle (cursor) will pop up as soon as I hover over something which has a hover effect. Same when I am clicking on something.

**Comment by fourminute** [comment]
Please try v2.4.0 and report back if the problem still exists.

**Comment by lookye** [comment]
Tried the v2.4 now. The problem is still there.
[Video.mov.zip](https://github.com/fourminute/Fluffy/files/2800109/Video.mov.zip)
In the zip is a short video. It is easier to what the problem is and I don´t know why app hangs and the cursor will get the loading circle as soon as I hover over the things. It takes ages if I want to use it.

**Comment by lookye** [comment]
I restartet my machine and now everything works as intendend. 
Thanks for your help!
