### ISSUE TITLE
Issue with USB installing on macOs

### ISSUE THREAD

**Issue by EddyCR** [fourminute/Fluffy#22]
Hello,

OS Version: macOS Mojave.
After running the **"fluffy.pyw"** and clicking "Select NSPs"  I get this error on the terminal:
![image](https://user-images.githubusercontent.com/5322460/51869268-ae799600-2315-11e9-8c41-87a4654fc4d4.png)

I can select the nsp to install from the finder/folder and the fluffly app shows me x nsps selected and after hit transfer and selecting the installation options on Goldleaf nothing happens and the GodLead screen only shows the "Starting Installation.." and in the Fluffy app it doesn't show any signals of progress.
![image](https://user-images.githubusercontent.com/5322460/51869932-cb16cd80-2317-11e9-869b-16d4a404f509.png)

Any ideas of what could be going on

Thanks and advance,
Eddy

**Comment by fourminute** [comment]
Goldleaf does not support multiple NSP installs and is usually very unstable. However, I need more time to look into this issue. Thanks for the report.

**Comment by EddyCR** [comment]
Thanks for answering. I only selected one nsp but it says  "2 NSPs selected" but from the modal opened i only selected one nsp, i tried several times, but it doesn't matter always says one selected.

**Comment by fourminute** [comment]
This will be fixed in 2.5.0 it's a bug with PyQt5's File Dialog process.

**Comment by EddyCR** [comment]
Understood. Thank you so much for looking into it.

**Comment by fourminute** [comment]
I'm glad ! Also about the white text, that is due to your system's theme, this is why dark mode has been enabled by default.
