### ISSUE TITLE
getting pyqt5 error on windows

### ISSUE THREAD

**Issue by Burgos91** [fourminute/Fluffy#23]
I been trying to use the app but I keep getting this error:
"DEBUG:root:Fluffy Log: If you see nothing here. Good!
ERROR:root:No module named PyQt5
Traceback (most recent call last):
  File "C:\Users\angel\Desktop\fluffy\fluffy.pyw", line 52, in <module>
    from PyQt5 import QtWidgets
ImportError: No module named PyQt5"

I try re-installing everything a couple times but no luck on launching it

**Comment by fourminute** [comment]
You are using 32-bit Python.

**Comment by Burgos91** [comment]
I use 32bit

**Comment by Burgos91** [comment]
nevermind I found my problem I didnt notice that I have installed python 2.7 ty for your time
