### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by wang93wei** [fourminute/Fluffy#24]
I hope the author can support and adapt multiple languages.

**Comment by fourminute** [comment]
That is currently being worked on and will be in the next release (2.5.0).

**Comment by Sev73n** [comment]
> I hope the author can support and adapt multiple languages.

我已经帮忙完成了中文化的操作
也许你可以添加更多的语言？（繁体中文）

**Comment by wang93wei** [comment]
> That is currently being worked on and will be in the next release (2.5.0).

Thank you! I wish you have a nice day.
