### ISSUE TITLE
Reboot Fluffy without closing

### ISSUE THREAD

**Issue by Crissal1995** [fourminute/Fluffy#39]
Like title, would be good to "reboot" Fluffy without closing it and reopening it (cause Goldleaf right now supports just one nsp, so if you want to install X nsps you have to close and reopen fluffy and select Goldleaf above X times)

**Comment by fourminute** [comment]
If the previous install was successful you should be able to use Fluffy again for another install. I've implemented this feature in a recent release.

**Comment by Crissal1995** [comment]
Don't know, it was successful but Fluffy told me to close the app. Btw will try again tomorrow and let you know if it's working (btw I'm using latest version)

**Comment by Crissal1995** [comment]
Yes my bad, was using an old rel
