### ISSUE TITLE
SegFault archlinux

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#4]
With fluffy at 03fc7c10e4099a30d7307542d44ffcc49878fb8c
I get:
```
$ ./fluffy.pyw       
[1]    26812 segmentation fault (core dumped)  ./fluffy.pyw
```
It's solved if I comment Qdarkstyle related code:
```
#import qdarkstyle
#app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
```
NB: qdarkstyle was not installed via pip but via arch aur:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-qdarkstyle

**Comment by fourminute** [comment]
That's interesting. Thank you for this report. So it's fixed now? I believe this might be exclusive to Arch.

**Comment by fourminute** [comment]
This bug has been fixed in v1.8.0 commit cb99a42d130266ce44669e62dc9316afcf09ed9b. Thank you =)

**Comment by YoyPa** [comment]
Just tested 87f00218a2b40269733ae7e6e9051819de8b847c, and It SegFault. :innocent: 
Replacing:
https://github.com/fourminute/Fluffy/blob/87f00218a2b40269733ae7e6e9051819de8b847c/fluffy.pyw#L48
With ```app = QtWidgets.QApplication(sys.argv)``` solves it.

**Comment by YoyPa** [comment]
@fourminute Have you seen the one above ? (can't reopen issue).
