### ISSUE TITLE
Name and author accuracy

### ISSUE THREAD

**Issue by XorTroll** [fourminute/Fluffy#41]
Despite being originally from Adubbz, he gave me the main developer role of Tinfoil, way before even Goldleaf was planned to be a thing. So I think it would be more simple to put Tinfoil and Goldleaf, and not the authors' names.

**Comment by fourminute** [comment]
Sounds like a good edit, I'll change it in the next release.

**Comment by fourminute** [comment]
Fixed in 2.7.0
