### ISSUE TITLE
Constant 100% CPU usage

### ISSUE THREAD

**Issue by jkcclemens** [fourminute/Fluffy#47]
Whenever Fluffy is open, it consumes 100% of one CPU. This is due to your main loop, it looks like.

You could sleep 16ms when necessary (60fps) or block on receiving an event in the loop to solve the issue, but I'm not familiar enough with the project to say which is best.

**Comment by fourminute** [comment]
Known issue, unsure about how to fix it properly. Threading in Python isn't necessarily my strong suit, I'll admit. It may get fixed in the future.

**Comment by jkcclemens** [comment]
Was this fixed?
