### ISSUE TITLE
error installing python --with-tcl-tk.

### ISSUE THREAD

**Issue by TTTechnoPro** [fourminute/Fluffy#48]
Hi! I'm trying to run Fluffy on macOS. And I've installed libusb and configparser. I'm having a hard time installing python --with-tcl-tk.
It shows an error saying Invalid Option:  --with-tcl-tk

Can you please help me with this

**Comment by fourminute** [comment]
I don't own a Mac, I unfortunately wouldn't be able to assist you debug this issue. However, please research via Google on how to install Python in MacOS with Tkinter. That will solve your issue. 

TCL-TK = Tkinter. Hope this helps =)

**Comment by MMeldrum** [comment]
For anyone still coming across this issue, the instructions in the README.md didn't work with Python 3.7.3 but did work with Python 3.10.6.
