### ISSUE TITLE
Corrupted data when install nsp with Usb Fluffy

### ISSUE THREAD

**Issue by lib211401** [fourminute/Fluffy#49]
My sd card is samsung evo 128gb , fat32 and im using v11.11.1 Kosmos. Install  nsp  with recommended TinFoil Usb Fluffy is no problem. but when i check data and got this message : " corrupted data was found " with every nsp installed with fluffy tinfoil usb. open Zelda Botw, playing  and i got a random freeze system at loading scene or after boss fight cutscene and need to restart Switch. Nsp games installed directly from sd card are no corrupt data like fluffy tinfoil usb. Can you help me ? Thank you. Anyway my type c usb cable is from Nintendo Pro Controller
Sorry for my bad English. Also checked nsp games with NSPVerify v1.01 before install and all of my nsp are ok

**Comment by fourminute** [comment]
Are there any logs in fluffy.log? If the install operation succeeded successfully then it’s difficult to say why or how your game became corrupted. It’s important to note that TinFoil is not being developed any longer, so you should try Goldleaf to see if it alleviates your issue.

I have never ran into this issue with over 100 different NSP installs and counting on several different systems and different Switch’s. It could very well be that the NSP is corrupt, even if it verifies correctly. NSP installations are foreign by nature and are still homebrew objects, remember that.

**Comment by lib211401** [comment]
thanks for reply Fourminute ! . 
fluffy logs :"  DEBUG:root:Fluffy Log: If you see nothing here. Good! ". i think my nsp is the problem. :)
