### ISSUE TITLE
Mac OS Mojave Error: invalid option: --with-tcl-tk

### ISSUE THREAD

**Issue by ristodesign** [fourminute/Fluffy#50]
Sadly brew is not accepting the brew reinstall python --with-tcl-tk

Any other way to get it going?

Thanks!

**Comment by GuillaumeJulien** [comment]
Hey ! 
Brew has delete this option (see: https://github.com/Homebrew/homebrew-core/pull/34424)
you can run this : 
`brew install tcl-tk
 brew reinstall python3
 pip3 install configparser
 python3 ./fluffy.pyw`

**Comment by ristodesign** [comment]
Hmm somehow it didn't work, but found this command to get me on the run.
sudo pip3 install pyusb pyqt5 libusb libusb1 qdarkstyle

**Comment by fourminute** [comment]
Glad you found a fix!

**Comment by farzadso** [comment]
@fourminute I had to do the same thing @ristodesign did on my mac to get fluffy to work. Do you want me to add it to the readme by opening a pull request?

**Comment by fourminute** [comment]
Hey @farzadso, I actually only just now saw your reply, for some reason I didn't get a notification for it. 

I've since added this to the ReadMe and have included credit to @GuillaumeJulien. 

Thank you @GuillaumeJulien for that fix!

**Comment by farzadso** [comment]
@fourminute Thanks for the update. I'm sure it'll solve the problem for many users.
