### ISSUE TITLE
PFS0.f never gets closed

### ISSUE THREAD

**Issue by friedkeenan** [fourminute/Fluffy#52]
As far as I can tell, the file handle for the PFS0 Fluffy opens never gets properly closed. I'm not too familiar with Fluffy's codebase, but from a glance it looks like a good spot for it might be in PFS0.reset()

**Comment by fourminute** [comment]
Thanks, will look into seeing if I can get this situated.

**Comment by fourminute** [comment]
fixed in release 2.8.0 =)
