### ISSUE TITLE
Goldleaf v0.5+ Support Information Inside

### ISSUE THREAD

**Issue by fourminute** [fourminute/Fluffy#53]
Due to the Paradise fire I'm still on the verge of being completely homeless so updates have been slower. I am still working on Fluffy however, don't worry.

As for Goldleaf v0.5+ support I am working on it.  I may wait for further Goldleaf USB improvements before making any changes however. This is due to the fact that it is in my opinion still not mature.

Right now Fluffy is confirmed and working for Goldleaf v0.4.

**Comment by friedkeenan** [comment]
Just so you don't have to do any digging, the only meaningful change for Goldtree clients in v0.5 is reading and writing the command magic and command id separately, so it's fairly trivial to add

**Comment by friedkeenan** [comment]
Oh and also, Goldleaf v0.6 is changing a ton about USB installs (you browse the files on the PC from the Switch), so you're going to have to rip out a ton of the code for Goldleaf. It also currently has some Windows-oriented stuff going on, but nothing's really set in stone at this point.

**Comment by fourminute** [comment]
Hey hows it going @friedkeenan. I've been checking up on Goldleaf development for periodically. I definitely think holding out on upgrading the Goldleaf code revision until the future releases. 

Also sorry for late reply.

**Comment by friedkeenan** [comment]
Honestly, the fix for Goldleaf v0.5 is so simple that you might as well make a new release for it since it's a lot of gain for your users and not a lot of work to add

**Comment by fourminute** [comment]
Yeah, you're probably right. I have another release scheduled I suppose I'll try to fit it in there!

**Comment by fourminute** [comment]
I reviewed your commit, very well done! If I end up using this as a reference I will _100%_ give you credit for this compatibility fix. Because I know how difficult it can be working with Goldleaf.

**Comment by fourminute** [comment]
fixed in release 2.8.0 =)
