### ISSUE TITLE
Feature: Adding support for blawar digableinc/tinfoil

### ISSUE THREAD

**Issue by tantoinet** [fourminute/Fluffy#55]
Is there any chance to add support for the digableinc/tinfoil nice NSP installer?
Also, please mention on the app which Tinfoil should be used.
The UI is excellent but the server side tool called Nut lacks multiplatform support

**Comment by pimpinpsp** [comment]
Closed sourced software should not be supported by open source software, especially ones with shady practices, IMO.

**Comment by fourminute** [comment]
@pimpinpsp The real MVP right here.
