### ISSUE TITLE
segfault on MacOS 10.14.4

### ISSUE THREAD

**Issue by SirSiggi** [fourminute/Fluffy#56]
Fluffy (any version, also 2.8.0) segfaults on my Mac running MacOS 10.14.4.

Switch: FW 8.0.1 with Kosmos 12.1.2

The segfault happens as soon as I plug in the Switch. Neither Tinfoil nor Goldleaf need to be started for it to happen. It also happened on earlier versions of fluffy and the Switch-FW.

If I can provide anymore useful information, feel free to ask.

```
➜  Downloads python3 fluffy\ \(1\).pyw
Python(12022,0x10dc8e5c0) malloc: Incorrect checksum for freed object 0x7f94371550f8: probably modified after being freed.
Corrupt value: 0x2807f9437181d0
Python(12022,0x10dc8e5c0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    12022 abort      python3 fluffy\ \(1\).pyw
```

[fluffy.log](https://github.com/fourminute/Fluffy/files/3188527/fluffy.log)
[fluffy.osxlog.txt](https://github.com/fourminute/Fluffy/files/3188529/fluffy.osxlog.txt)
<img width="535" alt="Bildschirmfoto 2019-05-16 um 20 41 59" src="https://user-images.githubusercontent.com/1073315/57878777-14355380-781b-11e9-987f-dd86a1a078cb.png">

**Comment by fourminute** [comment]
The Fluffy log is empty, not saying that Fluffy wasn't at fault but the chances of it being at fault are low. Please do note, that if USB install does not work you can still use Network Install.

Fixes issues related to MacOS has been extremely difficult for me as I don't own a Mac.

I will keep this issue open until resolved or if found that Fluffy isn't the problem(which I can't prove).

**Comment by kkirby** [comment]
Something to do with USB (duh) `libusb_get_device_list`

	* thread #2, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
	* frame #0: 0x00007fff6275c2c6 libsystem_kernel.dylib`__pthread_kill + 10
	frame #1: 0x00007fff62817bf1 libsystem_pthread.dylib`pthread_kill + 284
	frame #2: 0x00007fff626c66a6 libsystem_c.dylib`abort + 127
	frame #3: 0x00007fff627d516b libsystem_malloc.dylib`malloc_vreport + 545
	frame #4: 0x00007fff627edf01 libsystem_malloc.dylib`malloc_zone_error + 183
	frame #5: 0x00007fff627d1947 libsystem_malloc.dylib`tiny_free_list_remove_ptr + 544
	frame #6: 0x00007fff627cf318 libsystem_malloc.dylib`tiny_free_no_lock + 934
	frame #7: 0x00007fff627cee75 libsystem_malloc.dylib`free_tiny + 480
	frame #8: 0x00000001102e1de3 IOUSBLib`IOUSBDeviceClass::~IOUSBDeviceClass() + 83
	frame #9: 0x00000001102e1e95 IOUSBLib`IOUSBDeviceClass::~IOUSBDeviceClass() + 15
	frame #10: 0x00000001102e18f1 IOUSBLib`IOUSBIUnknown::release() + 33
	frame #11: 0x000000011029165a libusb-1.0.dylib`darwin_get_device_list + 150
	frame #12: 0x000000011028d506 libusb-1.0.dylib`libusb_get_device_list + 136
	frame #13: 0x000000011023e397 _ctypes.cpython-37m-darwin.so`ffi_call_unix64 + 79
	frame #14: 0x000000011023eb53 _ctypes.cpython-37m-darwin.so`ffi_call + 703
	frame #15: 0x000000011023a47e _ctypes.cpython-37m-darwin.so`_ctypes_callproc + 647
	frame #16: 0x0000000110234e78 _ctypes.cpython-37m-darwin.so`PyCFuncPtr_call + 499
	frame #17: 0x00000001000e8a39 Python`_PyObject_FastCallKeywords + 359
	frame #18: 0x000000010017e65e Python`call_function + 746
	frame #19: 0x0000000100177231 Python`_PyEval_EvalFrameDefault + 7016
	frame #20: 0x00000001000e8fae Python`function_code_fastcall + 112
	frame #21: 0x00000001000e9931 Python`_PyObject_Call_Prepend + 150
	frame #22: 0x000000010012705c Python`slot_tp_init + 80
	frame #23: 0x0000000100123d28 Python`type_call + 178
	frame #24: 0x00000001000e8a39 Python`_PyObject_FastCallKeywords + 359
	frame #25: 0x000000010017e65e Python`call_function + 746
	frame #26: 0x00000001001772cf Python`_PyEval_EvalFrameDefault + 7174
	frame #27: 0x00000001000e8fae Python`function_code_fastcall + 112
	frame #28: 0x000000010017e665 Python`call_function + 753
	frame #29: 0x0000000100177218 Python`_PyEval_EvalFrameDefault + 6991
	frame #30: 0x00000001000f4762 Python`gen_send_ex + 242
	frame #31: 0x0000000100173bad Python`builtin_next + 99
	frame #32: 0x00000001000e9637 Python`_PyMethodDef_RawFastCallKeywords + 496
	frame #33: 0x00000001000e8bd3 Python`_PyCFunction_FastCallKeywords + 44
	frame #34: 0x000000010017e5f0 Python`call_function + 636
	frame #35: 0x00000001001772cf Python`_PyEval_EvalFrameDefault + 7174
	frame #36: 0x00000001000e8fae Python`function_code_fastcall + 112
	frame #37: 0x000000010017e665 Python`call_function + 753
	frame #38: 0x0000000100177231 Python`_PyEval_EvalFrameDefault + 7016
	frame #39: 0x000000010017eef7 Python`_PyEval_EvalCodeWithName + 1835
	frame #40: 0x00000001000e8b98 Python`_PyFunction_FastCallKeywords + 225
	frame #41: 0x000000010017e665 Python`call_function + 753
	frame #42: 0x0000000100177375 Python`_PyEval_EvalFrameDefault + 7340
	frame #43: 0x00000001000e8fae Python`function_code_fastcall + 112
	frame #44: 0x000000010017e665 Python`call_function + 753
	frame #45: 0x00000001001772cf Python`_PyEval_EvalFrameDefault + 7174
	frame #46: 0x000000010017eef7 Python`_PyEval_EvalCodeWithName + 1835
	frame #47: 0x0000000100175626 Python`PyEval_EvalCode + 51
	frame #48: 0x00000001001a42a5 Python`run_mod + 54
	frame #49: 0x00000001001a32c0 Python`PyRun_FileExFlags + 164
	frame #50: 0x00000001001a297a Python`PyRun_SimpleFileExFlags + 266
	frame #51: 0x00000001001bb6a2 Python`pymain_main + 5614
	frame #52: 0x00000001001bbca4 Python`_Py_UnixMain + 56
	frame #53: 0x00007fff626213d5 libdyld.dylib`start + 1
	(lldb)
