### ISSUE TITLE
[Arch AUR package] where should config/log belong ?

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#57]
Hello,
Following the recent .config/fluffy issue and a comment from Arvedui(arch AUR) I'm hesitating on how to handle fluffy.conf and fluffy.log.

Got multiple options, but none is perfect:
 - Use ~/.config/fluffy, ppl complain about making a directory in /home + it's not functional on a multiuser install. (.desktop file point in $USER_A folder even if launched by $USER_B)
 - Use ~/.config, no more directory creation :+1:  + it's still not functional on a multiuser install.
 - Use /tmp, only problem is the config file being erased on each reboot.
 - Use /var/tmp, config file will be erased every 30days (manjaro default, not sure for arch)

Options 4 and 2 are better, then what's more valuable, multiuser compatibility or persisting config file :thinking:. Searching NSP from /tmp or /var/tmp via tkinter is a bit more annoying as tkinter filedialog show no shortcut to home.

NB: Folder is determined by ```Path=``` in https://github.com/fourminute/Fluffy/blob/master/linux/fluffy.desktop. It also affect the default folder opened by tkinter filedialog.

An other solution but more annoying for you is to handle it in fluffy, detecting os=linux then read/write in $HOME/.config/ instead of current folder.

**Comment by fourminute** [comment]
Hmmm...  2 seems great to be honest.  That's a great idea on the last bit. Consider it done, in the next version I will make the config write to $HOME/.config/ for linux users. Any idea where I should write the config for mac users(I don't own a mac).?

**Comment by fourminute** [comment]
In my own testing I can't create any logs inside .config with default permissions. Where else could we log?

**Comment by YoyPa** [comment]
> Any idea where I should write the config for mac users(I don't own a mac).

I have no clue how osx work, but if we look at GIMP manual for inspiration:
```
In OSX:
/Users/{your_id}/Library/GIMP/2.8/
or possibly
/Users/{your_id}/Library/Application Support/GIMP/2.8/
(this could depend on the GIMP build you use).
```
source: https://www.gimp.org/tutorials/GIMPProfile/

> I've decided to go for creating a folder in $HOME called .fluffy and putting all the fluffy related files in there. So far I've ran into zero issues. Let me know what you think.

That's as good as .config in my opinion :+1:

**Comment by fourminute** [comment]
You may try out the nightly branch where this change(among many other changes) has been applied.

**Comment by fourminute** [comment]
Check out the new release!
