### ISSUE TITLE
Windows Defender detects "Fuerboos.E!cl" in v2.9.1 fluffy.exe 

### ISSUE THREAD

**Issue by oniietzschan** [fourminute/Fluffy#59]
![image](https://user-images.githubusercontent.com/5661349/58489641-a998e780-8139-11e9-8e57-f0b753c85ac5.png)

I imagine that it's possible that this is a false positive. In that case, some explanation in the Troubleshooting Tips, or possibly a note in the release description would be helpful. Thanks!

**Comment by fourminute** [comment]
Yes I noticed some false detection going on in VirusTotal, too. I'm really not sure why it's happening and to be honest I'd rather try to fix the false positive than circumvent around it that way people don't think of Fluffy as being malicious.
