### ISSUE TITLE
[About Window] Wrong position for the close button

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#61]
Hello,
When opening the "About" window, the close button is shifted to the left.
![Screenshot_20190530_130418](https://user-images.githubusercontent.com/29115747/58629112-07106e00-82cb-11e9-98b0-60be91e15048.png)

It only happen the first time I click "About", if I reopen it a second time it fix itself.

System info:
KDE/Kwin 5.15.5, Breeze.

**Comment by fourminute** [comment]
interesting. But it might have to do with KDE. I’m not sure. I’ll test it out on KDE.

**Comment by xTibor** [comment]
Not your issue, it's some kind of KWin race condition bug. Trivial to reproduce by hammering the window resizing functions: 

https://user-images.githubusercontent.com/1627292/106954506-303a0080-6734-11eb-9681-07e63c354aef.mp4
