### ISSUE TITLE
[About Window] There is no interaction possible with your monero address

### ISSUE THREAD

**Issue by YoyPa** [fourminute/Fluffy#62]
Hello,
It's impossible to copy/paste your monero address.
It's impossible to resize the window to show it fully, only a scroll bar.

PS: An unrelated suggestion: QRcode:
![Screenshot_20190530_132030](https://user-images.githubusercontent.com/29115747/58629834-11336c00-82cd-11e9-80ca-a14c05bdc932.png)
KDE klipper or qrencode can do them easily.

**Comment by fourminute** [comment]
That’s not a bad idea. I’ll see what I can do for next release.
