### ISSUE TITLE
Version pyw 2.9.1  MacOS - How to add nsp files

### ISSUE THREAD

**Issue by matteopiccioni** [fourminute/Fluffy#63]
If I try to start the script using 'python3.7 fluffy.pyw' the gui appears,
on console I have the following messages:

> libpng warning: iCCP: CRC error
> libpng warning: iCCP: CRC error
> libpng warning: iCCP: CRC error

In the GUI when I select 'Goldenleaf' option, I cannot see a way to add nsp files. I only see the 'Begin Transfer' button. If I click it, I can read the message 'Awaiting selection.'
How should I do?
Thanks

**Comment by farzadso** [comment]
Same happens for me

**Comment by fourminute** [comment]
This is normal and intended. For Goldleaf v0.6 there is no longer NSP selection via PC. You will need to use the recommended Goldleaf.nro. As for why it won’t recognize the USB connection I will need more information please open another issue with relevant logs.
