### ISSUE TITLE
Fluffy 2.9.1 not working on Linux

### ISSUE THREAD

**Issue by nitro322** [fourminute/Fluffy#64]
Prior versions have worked fine, but 2.9.1 doesn't work for me under Linux.  I get the following error if trying to launch the script through python:

```
$ python3 ./Apps/Fluffy/2.9.1/fluffy.pyw
  File "./Apps/Fluffy/2.9.1/fluffy.pyw", line 1188
    os.rename(path, f"{os.path.dirname(path)}/{new_name}"
```

And if I make it executable and try to directly execute it it acts even weirder:

```
$ ./fluffy.pyw
./fluffy.pyw: line 1: #!: command not found
./fluffy.pyw: line 7: $'\nCute': command not found
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
./fluffy.pyw: line 36: try:: command not found
./fluffy.pyw: line 37: syntax error near unexpected token `('
./fluffy.pyw: line 37: `    if "win" in sys.platform[:3].lower():'
```

2.8.0 worked perfectly fine.  Some additional details about my environment:

Gentoo amd64
python 3.5.5
QT 5.12.3

Not sure what additional info my help, but please let me know and I'll be happy to provide it.

Thanks!

**Comment by fourminute** [comment]
I will create a Linux executable for those on Linux with compatibility issues. Though to be fair I think this is down to system configuration as I've tested v2.9.1 on several different Linux machines and found no issues thus far.

**Comment by fourminute** [comment]
Please try this nightly version of Fluffy:
https://raw.githubusercontent.com/fourminute/Fluffy/nightly/fluffy.pyw

**Comment by nitro322** [comment]
Thanks for the extremely fast response.  New version loads perfectly now both when called as a python script and when executed directly.  Haven't had a chance to test using it to install an NSP, but you nailed the reported problem.

One interesting addition - I did a diff of 2.9.1 to the above nightly just because I was curious and see that the main change related to this seemed to be changing the path like so:

```
os.rename(path, new_name)
```

Easy enough.  However, there also seems to be something funky at the beginning of the file in 2.9.1, before the #!.  Running a diff gives me this:

```
--- 2.9.1/fluffy.pyw    2019-06-03 11:50:15.954087744 -0500
+++ 20190604/fluffy.pyw 2019-06-04 21:34:23.810703121 -0500
@@ -1,4 +1,4 @@
-#! /usr/bin/env python3
+#! /usr/bin/env python3
```

It's showing some kind of difference there, but I couldn't see what it was until I piped the diff output to Vim, which then showed me this:

```
--- 2.9.1/fluffy.pyw	2019-06-03 11:50:15.954087744 -0500
+++ 20190604/fluffy.pyw	2019-06-04 21:34:23.810703121 -0500
@@ -1,4 +1,4 @@
-﻿﻿<feff>#! /usr/bin/env python3
+#! /usr/bin/env python3
```

That <feff> is some kind of control character (apparently a byte order mark?) that's not normally visible, even when copy/pasting (I had to manually type it in to this input box.  I think that's what caused my box to go haywire when directly executing the previous version, whereas calling it through python simply reported the syntax error.

Just wanted to give you a heads up about it.  Not sure where that may have come from, but a quick google search shows that it can show up unexpectedly and cause problems.

Anyway, again, appreciate the quick response, and all your work on this in general.  Love being able to work with my Switch from Linux.

**Comment by fourminute** [comment]
I'm glad! Please let me know if NSP installs work once you get a chance to test it out.

**Comment by nitro322** [comment]
Installation via tinfoil works.  I also tried testing via the newer version of Goldleaf, but couldn't figure out how - Fluffy doesn't appear to let me specify an NSP in Goldleaf mode, and I couldn't find an option for installing software Goldleaf, only browsing/managing existing software.  I'm clearly missing something, but tinfoil works well enough for me, so I'm not too stressed over that.  :-)

**Comment by fourminute** [comment]
That is normal, there is no longer NSP selection for Goldleaf mode. Now Goldleaf lets you browse your PC files and install NSP's individually.

**Comment by alimao10** [comment]
switch not detected . fluffy  to linux only works usb ports 3.0  ?
