### ISSUE TITLE
Korean Translation for Fluffy

### ISSUE THREAD

**Issue by DDinghoya** [fourminute/Fluffy#66]
"Fluffy" - Fluffy
"Begin Transfer" - 전송 시작
"Switch IP" - 스위치 IP
"This Computer's IP" - 이 컴퓨터의 IP
"USB Transfer Mode" - USB 전송 모드
"Normal Mode" - 일반 모드
"Safe Mode" - 안전 모드
"Current NSP" - 현재 NSP
"Successfully Installed" - 성공적으로 설치되었습니다.
"Awaiting Selection" - 선택을 기다리고 있습니다.
"Switch Not Detected" - 스위치가 감지되지 않았습니다.
"Switch Detected" - 스위치가 감지되었습니다.
"Network Mode" - 네트워크 모드
"NSP Selection" - NSP 선택
"NSP(s) Selected" - 선택된 NSP
"Awaiting Connection Request" - 연결 요청 대기 중
"Cancel" - 취소
"Error: Goldleaf threw an exception." - 오류: Goldleaf에서 예외가 발생했습니다.
"Error: Tinfoil threw an exception." - 오류: Tinfoil에서 예외가 발생했습니다.
"Error: Network threw an exception." - 오류: 네트워크에서 예외가 발생했습니다.
"Dark Mode" - 어두운 모드
"Options" - 옵션
"Language" - 언어
"Github" - Github
"Network" - 네트워크
"Headers Sent" - 헤더 보내기
"NSP(s) in Queue" - 대기열의 NSP
"Installing" - 설치
"Transfer Rate" - 전송율
"Current NCA" - 현재 NCA
"About" - 소개
"Special Thanks" - 특별 감사
"Donate" - 기부

**Comment by fourminute** [comment]
Thank you! I will add this to Fluffy. Great work.

**Comment by DDinghoya** [comment]
Thank you for your reply!! :)
