### ISSUE TITLE
Can't Get USB Connected MacOS 

### ISSUE THREAD

**Issue by farzadso** [fourminute/Fluffy#67]
Hi

I'm using the same Nintendo Switch with the same cable I used to on a newer Macbook and I can't get fluffy to connect. The USB connection screen is idle on both the Goldleaf and Tinfoil versions you have provided. It's strange as I have done the same steps as I had earlier on another device. Also, the USB cable is working properly as I can properly inject payloads to it.

I see this warning in the console after opening fluffy : 

```bash
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
```

In this issue (https://github.com/fourminute/Fluffy/issues/63) you said you need more logs. What kind of logs do you want?

**Comment by fourminute** [comment]
Hmm, I'll look into this. It's worth noting that the recent release of Fluffy **v2.9.0+** is an astronomical change to the code structure. It's very possible that something has changed that could make MacOS compatibility problematic. 

Can you please provide the Fluffy.log. Also please try version 2.8.0 and report back.

**Comment by fourminute** [comment]
Please try this nightly version of Fluffy:
https://raw.githubusercontent.com/fourminute/Fluffy/nightly/fluffy.pyw

**Comment by farzadso** [comment]
Thanks for the reply. I tried v2.8.0 and I had no luck in opening it.

This is the view I have on v2.9.1 👇

![Screen Shot 2019-06-09 at 3 45 44 pm](https://user-images.githubusercontent.com/19854715/59158311-b15b7300-8acd-11e9-96f1-2d0917f25313.png)

This is the log you requested : 

```
DEBUG:root:Fluffy Log: If you see nothing here. Good!
ERROR:root:No backend available
Traceback (most recent call last):
  File "./fluffy2.9.1.pyw", line 1747, in check_usb_success
    connect_switch()
  File "./fluffy2.9.1.pyw", line 692, in connect_switch
    global_dev = usb.core.find(idVendor=0x057E, idProduct=0x3000)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

It's noteworthy that using other apps, such as AluminumFoil works flawlessly with my cable.

**Comment by farzadso** [comment]
@fourminute Any updates?

**Comment by mhqschen** [comment]
Got same error on my mac as well.

**Comment by fourminute** [comment]
Functionality-wise, does Fluffy still work despite the CRC warning? I don't own a Mac, so any help would be appreciated on this issue. It's a Mac specific bug for certain.

**Comment by mhqschen** [comment]
No, the python will crash along with the warning.
How can I provide more information on this issue? 

The warning I got:

> python3 /users/xxxx/downloads/fluffy.pyw                        
Config not found: '/Users/xxxx/fluffy.conf'
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
[1]    1402 segmentation fault  python3 /users/xxxx/downloads/fluffy.pyw

**Comment by andrewmiskell** [comment]
Try installing libusb via brew instead of pip3. That fixed the issue for me.

**Comment by mhqschen** [comment]
> Try installing libusb via brew instead of pip3. That fixed the issue for me.

Thanks for the help but still no luck...

**Comment by farzadso** [comment]
@andrewmiskell @mhqschen  Same here

**Comment by Trunkzeh** [comment]
> Try installing libusb via brew instead of pip3. That fixed the issue for me.

This just worked for me. Goldleaf & USB install were not showing up; did brew install libusb and restart Fluffy and all was well.

**Comment by ahmadnbl** [comment]
> Try installing libusb via brew instead of pip3. That fixed the issue for me.

Tthis worked for me. And as @Trunkzeh said, I just install `libusb` through `brew` with that command
```
brew install libusb
```

@fourminute I think you can update the readme to install `libusb` via `brew` instead `pip3`

**Comment by Yamilquery** [comment]
I tried uninstalling pip3 from python and installing with brew, but I'm still having the same issue. :(

**Comment by farzadso** [comment]
@Yamilquery I couldn't get it to work. Switched to `nut` instead.
