### ISSUE TITLE
Replace .exe with .pyz

### ISSUE THREAD

**Issue by Crissal1995** [fourminute/Fluffy#69]
Exe is a bad format, compatible with only Windows and, when not signed, will cause problems (false positive) with antiviruses.
Pyz (python zip) is good because it's supported by Python itself (`zipapp` is part of their library), can pack other modules in it (the ones required in requirements.txt) and it's compatible with all the OSs.

If you're interested, [here is their ref/guide](https://docs.python.org/3/library/zipapp.html#creating-standalone-applications-with-zipapp).
The only thing is, Python >=3.5 is required

**Comment by fourminute** [comment]
Thanks I'll check it out.

**Comment by Crissal1995** [comment]
Oh and btw you can also use `pyzw` extension (same result as you do with `pyw`)
