### ISSUE TITLE
Ubuntu - Invalid USB Command (5)

### ISSUE THREAD

**Issue by rzdev** [fourminute/Fluffy#72]
When trying to install using "USB Installalation" on goldleaf, then clicking on "Begin Transfer" on Fluffy, an error occured:

An error occured attempting to process USB GLUC Commands:

Error : 0xb64
Module : Goldleaf (356)
Description : Invalid USB Command (5)

Version:
Goldleaf 0.5
Fluffy 2.9.2
Ubuntu 16.04

**Comment by fourminute** [comment]
Not a bug, Fluffy 2.9.2 isn't compatible with Goldleaf v0.5. Use recommended Goldleaf.nro file.
