### ISSUE TITLE
Recommended GoldLeaf freezes when opening folder with large nsp

### ISSUE THREAD

**Issue by glencoe2004** [fourminute/Fluffy#73]
Basically what happens is when you enter a directory with a large NSP while using Fluffy + GoldLeaf, the GoldLeaf browser completely freezes, and the only way to get out is to unplug the usb.

I would post a log, but Fluffy does not log the problem.

**Comment by fourminute** [comment]
Yep that is a Goldleaf but not related to Fluffy.
