### ISSUE TITLE
Image not found & Failed to import tkinter on macos

### ISSUE THREAD

**Issue by essalie** [fourminute/Fluffy#78]
Am I being mad? I've never got on with python...
👋 ❯ python3 ./fluffy.pyw
Error: Failed to import Tkinter.
dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload/_tkinter.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.4/Tcl
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload/_tkinter.so
  Reason: image not found

everything installed correctly and i set all the appropriate set arguements it told me to... still throwing that at me. tried cloning and running in like that, nada!

**Comment by fourminute** [comment]
Let me know when you've found a reasonable fix. I know nothing about MacOS. Thanks.
