### ISSUE TITLE
Switching to Goldleaf - options disappear

### ISSUE THREAD

**Issue by gut5** [fourminute/Fluffy#79]
Fluffy 2.9.2 bug (doesn't affect 2.8.0), switching to Goldleaf with the radio buttons causes the buttons to select NSP and other buttons to disappear.

**Comment by lookye** [comment]
Thats correct and no Bug. As of Goldleaf 0.6 you wont need that anymore. You just click "Begin Transfer" and select the NSP in Goldleaf.

**Comment by fourminute** [comment]
Thanks for the response @lookye
