### ISSUE TITLE
Options missing on Mac/Python3

### ISSUE THREAD

**Issue by reneroth** [fourminute/Fluffy#83]
<img width="292" alt="Screenshot 2019-09-26 at 09 07 45" src="https://user-images.githubusercontent.com/11065422/65666067-2cc14000-e03d-11e9-87f9-ac07aa002170.png">

As you can see, the options for goldleaf and USB are missing. Latest python3 & pip3 from homebrew (`3.7.4`&& `19.1.1`), dependencies installed as in current Readme.

Thank you for a cool tool!

**Comment by rodrigovive** [comment]
Hi, you need to install libusb
 `brew install libusb`
