### ISSUE TITLE
Linux (openSUSE and Archlinux) and MacOS not working

### ISSUE THREAD

**Issue by pseiler** [fourminute/Fluffy#85]
I tried to get latest commit on fluffy (f59b8d4536890f1aa2b48b2e72dffa38d27e69d9) and it didn't work with Goldleaf 0.7.3.

I installed the udev rule and fluffy detects the switch correctly.
But when I press "Begin transfer" and press "PC Drive (via USB)" on my Switch nothing happens anymore. I cannot browse files on the switch. When I press "Cancel" in fluffy Goldleaf only shows "Select file from PC" with nothing more to do. I only can press **B** to go back and try again with the same result. 

As long as fluffy is in transfer mode and press "PC Drive (via USB)" on the switch, I cannot do anything on the switch anymore. No button presses have any effect until I cancel fluffy.

The logs in $HOME/.fluffy/fluffy.log are empty (except the message ```[...]If you see nothing here. Good!```. 

I use openSUSE Linux x86_64 with kernel "4.12.14-lp151.28.20-default"
I also used several USB ports. Back in the days I successfully transfered files from this computer with legacy tinfoil and the usb companion python script

The only thing I get when running fluffy on stdout when running fluffy in a terminal is the following
```
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
libpng warning: iCCP: CRC error
```

**Comment by CodingKoopa** [comment]
Reproduced this issue on Arch Linux.

**Comment by cerezo074** [comment]
Reproduced this issue on OSX latest mohave version. I've got stuck on the switch UI(i just can see "select file from pc").

**Comment by brando56894** [comment]
Doesn't work for me either on Arch, either using the package from the AUR or from here. It detects my switch, but when I try and use tinfoil via USB it shows "error: tinfoil threw an exception" and the network method just hangs at "Transferring NSP header"

Using the newest version of Goldtree with the goldtree method just hangs, trying to use the "recommended" version crashes my switch upon opening. I'm using v9 of Horizon.

**Comment by tr1p0p** [comment]
Same. No programm work on linux for usb switch install. Kind of lame..
