### ISSUE TITLE
'Switch Not Detected' (Atmosphere 10.2)

### ISSUE THREAD

**Issue by Bonethugs1980** [fourminute/Fluffy#86]
It appears with the new Atmosphere update with 10.2, the hid mitm support was partially removed (can be re enabled but no clear from usual community responses).

Fluffy does not see or recognize the switch for NSP installs via libusbK.  Doesn't make a difference in Zadig ('List all Devices'); Goldleaf is detected if use the .nro, but nothing can be installed.  The 'Nintendo Switch' is recognized in the list as well. Reinstalling or replacing the drivers in Zadig doesn't appear to affect it either. 

You may be aware off this already?

**Comment by deadair3210** [comment]
Are you sure it's the new atmosphere build and not the new goldleaf build if you are using that? It recently changed how USB comm worked and tools have to be updated to support it

**Comment by Bonethugs1980** [comment]
no difference with new goldleaf and tinfoil (I had an issue with Lithium, while associating the jar application.  Didn't bother with this)

As far as I know I updated all the necessary Atmosphere files, Kosmos etc to the current releases/updates...

**Comment by Bonethugs1980** [comment]
Please close this issue (probably added the comments to this section too quickly), I was able to use awoo installer.nro instead which was perfectly compatible with fluffy with the tinfoil setting. 

Cheers.

**Comment by Bonethugs1980** [comment]
Closing.
