### ISSUE TITLE
Remote PC (via USB) hangs indefinitely 

### ISSUE THREAD

**Issue by iDVB** [fourminute/Fluffy#89]
USB seems to work and detects NSW
I open Goldleaf > Explore Content on the NSW 
Then I click on "Begin Transfer" on Fluffy....
and get this...
![image](https://user-images.githubusercontent.com/189506/90921553-78e54380-e3b8-11ea-8365-38b19cc0015f.png)

Then on the NSW I click on `Remote PC (via USB)` and it hangs indefinitely. 

What am I doing wrong?

**Comment by tr1p0p** [comment]
Same for me. This program (and all the program for linux for siwtch) just not working , even with udev rules.
